# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeAttach(DockerBaseRunner):
    """
    Usage:  docker compose attach [OPTIONS] SERVICE
    Attach local standard input, output, and error streams to a service's running container
    """

    detach_keys: Optional[str] = None
    """Override the key sequence for detaching from a container."""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    index: Optional[int] = None
    """index of the container if service has multiple replicas."""
    no_stdin: Optional[bool] = None
    """Do not attach STDIN"""
    sig_proxy: Optional[bool] = None
    """Proxy all received signals to the process (default true)"""
    _cmd: str = "attach"
    _options: List[str] = [
        "dry_run",
        "no_stdin",
        "sig_proxy",
    ]
