# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeAttach(DockerBaseRunner):
    """
    Usage:  docker compose attach [OPTIONS] SERVICE
    Attach local standard input, output, and error streams to a service's running container
    """

    detach_keys: Optional[str] = None
    """Override the key sequence for detaching from
       a container."""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    index: Optional[int] = None
    """index of the container if service has
       multiple replicas."""
    no_stdin: Optional[bool] = None
    """Do not attach STDIN"""
    sig_proxy: Optional[bool] = None
    """Proxy all received signals to the process
       (default true)"""
    _cmd: str = _dc.field(default="attach", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "no_stdin",
            "sig_proxy",
        ],
        repr=False,
        init=False,
    )
