# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeBuild(DockerBaseRunner):
    """
    Usage:  docker compose build [OPTIONS] [SERVICE...]
    Build or rebuild services
    """

    build_arg: Optional[list] = None
    """Set build-time variables for services"""
    builder: Optional[str] = None
    """Set builder to use"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    memory: Optional[str] = None
    """Set memory limit for the build container. Not supported by BuildKit."""
    no_cache: Optional[bool] = None
    """Do not use cache when building the image"""
    pull: Optional[bool] = None
    """Always attempt to pull a newer version of the image"""
    push: Optional[bool] = None
    """Push service images"""
    quiet: Optional[bool] = None
    """Don't print anything to STDOUT"""
    ssh: Optional[str] = None
    """Set SSH authentications used when building service images. (use 'default' for using your default SSH Agent)"""
    with_dependencies: Optional[bool] = None
    """Also build dependencies (transitively)"""
    _cmd: str = "build"
    _options: List[str] = [
        "dry_run",
        "no_cache",
        "pull",
        "push",
        "quiet",
        "with_dependencies",
    ]
