# DO NOT EDIT: Autogenerated by /Users/micha/dev/external/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.17.3

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeBuild(DockerBaseRunner):
    """
    Usage:  docker compose build [OPTIONS] [SERVICE...]
    Build or rebuild services
    """

    build_arg: Optional[list] = None
    """Set build-time variables for services."""
    no_cache: Optional[bool] = None
    """Do not use cache when building the image"""
    progress: Optional[str] = None
    """Set type of progress output (auto, tty, plain, quiet) (default "auto")"""
    pull: Optional[bool] = None
    """Always attempt to pull a newer version of the image."""
    push: Optional[bool] = None
    """Push service images."""
    quiet: Optional[bool] = None
    """Don't print anything to STDOUT"""
    ssh: Optional[str] = None
    """Set SSH authentications used when building service images. (use 'default' for using your default SSH Agent)"""
    _cmd: str = "build"
    _options: List[str] = [
        "no_cache",
        "pull",
        "push",
        "quiet",
    ]
