# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeBuild(DockerBaseRunner):
    """
    Usage:  docker compose build [OPTIONS] [SERVICE...]
    Build or rebuild services
    """

    build_arg: Optional[list] = None
    """Set build-time variables for services"""
    builder: Optional[str] = None
    """Set builder to use"""
    check: Optional[bool] = None
    """Check build configuration"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    memory: Optional[int] = None
    """Set memory limit for the build container.
       Not supported by BuildKit."""
    no_cache: Optional[bool] = None
    """Do not use cache when building the image"""
    print: Optional[bool] = None
    """Print equivalent bake file"""
    provenance: Optional[str] = None
    """Add a provenance attestation"""
    pull: Optional[bool] = None
    """Always attempt to pull a newer version of
       the image"""
    push: Optional[bool] = None
    """Push service images"""
    quiet: Optional[bool] = None
    """Suppress the build output"""
    sbom: Optional[str] = None
    """Add a SBOM attestation"""
    ssh: Optional[str] = None
    """Set SSH authentications used when
       building service images. (use 'default'
       for using your default SSH Agent)"""
    with_dependencies: Optional[bool] = None
    """Also build dependencies (transitively)"""
    _cmd: str = _dc.field(default="build", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "check",
            "dry_run",
            "no_cache",
            "print",
            "pull",
            "push",
            "quiet",
            "with_dependencies",
        ],
        repr=False,
        init=False,
    )
