# DO NOT EDIT: Autogenerated by src/docker_composer/_utils/generate_class.py
# for docker-compose version 1.25.0, build unknown

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeBundle(DockerBaseRunner):
    """
    Generate a Distributed Application Bundle (DAB) from the Compose file.

    Images must have digests stored, which requires interaction with a
    Docker registry. If digests aren't stored for all images, you can fetch
    them with `docker-compose pull` or `docker-compose push`. To push images
    automatically when bundling, pass `--push-images`. Only services with
    a `build` option specified will have their images pushed.

    Usage: bundle [options]

    """

    push_images: Optional[bool] = None
    """Automatically push images for any services
       which have a `build` option specified."""
    output: Optional[str] = None
    """Path to write the bundle file to.
       Defaults to "<project name>.dab"."""
    _cmd: str = "bundle"
    _options: List[str] = [
        "push_images",
    ]
