# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

from typing import Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeCommit(DockerBaseRunner):
    """
    Usage:  docker compose commit [OPTIONS] SERVICE [REPOSITORY[:TAG]]
    Create a new image from a service container's changes
    """

    author: Optional[str] = None
    """Author (e.g., "John Hannibal Smith
       <hannibal@a-team.com>")"""
    change: Optional[list] = None
    """Apply Dockerfile instruction to the created image"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    index: Optional[int] = None
    """index of the container if service has multiple
       replicas."""
    message: Optional[str] = None
    """Commit message"""
    pause: Optional[bool] = None
    """Pause container during commit (default true)"""
    _cmd: str = "commit"
    _options: list[str] = [
        "dry_run",
        "pause",
    ]
