# DO NOT EDIT: Autogenerated by src/docker_composer/_utils/generate_class.py
# for docker-compose version 1.25.0, build unknown

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeConfig(DockerBaseRunner):
    """
    Validate and view the Compose file.

    Usage: config [options]

    """

    resolve_image_digests: Optional[bool] = None
    """Pin image tags to digests."""
    no_interpolate: Optional[bool] = None
    """Don't interpolate environment variables"""
    quiet: Optional[bool] = None
    """Only validate the configuration, don't print
       anything."""
    services: Optional[bool] = None
    """Print the service names, one per line."""
    volumes: Optional[bool] = None
    """Print the volume names, one per line."""
    hash: Optional[str] = None
    """Print the service config hash, one per line.
       Set "service1,service2" for a list of specified services
       or use the wildcard symbol to display all services"""
    _cmd: str = "config"
    _options: List[str] = [
        "resolve_image_digests",
        "no_interpolate",
        "quiet",
        "services",
        "volumes",
    ]
