# DO NOT EDIT: Autogenerated by /Users/micha/dev/external/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeCp(DockerBaseRunner):
    """
    Usage:  docker compose cp [OPTIONS] SERVICE:SRC_PATH DEST_PATH|-
        docker compose cp [OPTIONS] SRC_PATH|- SERVICE:DEST_PATH
    Copy files/folders between a service container and the local filesystem
    """

    archive: Optional[bool] = None
    """Archive mode (copy all uid/gid information)"""
    follow_link: Optional[bool] = None
    """Always follow symbol link in SRC_PATH"""
    index: Optional[int] = None
    """Index of the container if there are multiple instances of a service ."""
    _cmd: str = "cp"
    _options: List[str] = [
        "archive",
        "follow_link",
    ]
