# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeCreate(DockerBaseRunner):
    """
    Usage:  docker compose create [OPTIONS] [SERVICE...]
    Creates containers for a service
    """

    build: Optional[bool] = None
    """Build images before starting containers"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    force_recreate: Optional[bool] = None
    """Recreate containers even if their configuration and image haven't changed"""
    no_build: Optional[bool] = None
    """Don't build an image, even if it's policy"""
    no_recreate: Optional[bool] = None
    """If containers already exist, don't recreate them. Incompatible with --force-recreate."""
    pull: Optional[str] = None
    """Pull image before running ("always"|"missing"|"never"|"build") (default "policy")"""
    quiet_pull: Optional[bool] = None
    """Pull without printing progress information"""
    remove_orphans: Optional[bool] = None
    """Remove containers for services not defined in the Compose file"""
    scale: Optional[str] = None
    """Scale SERVICE to NUM instances. Overrides the scale setting in the Compose file if present."""
    _cmd: str = "create"
    _options: List[str] = [
        "build",
        "dry_run",
        "force_recreate",
        "no_build",
        "no_recreate",
        "quiet_pull",
        "remove_orphans",
    ]
