# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeDown(DockerBaseRunner):
    """
    Usage:  docker compose down [OPTIONS] [SERVICES]
    Stop and remove containers, networks
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    remove_orphans: Optional[bool] = None
    """Remove containers for services not defined in
       the Compose file"""
    rmi: Optional[str] = None
    """Remove images used by services. "local" remove
       only images that don't have a custom tag
       ("local"|"all")"""
    timeout: Optional[int] = None
    """Specify a shutdown timeout in seconds"""
    volumes: Optional[bool] = None
    """Remove named volumes declared in the "volumes"
       section of the Compose file and anonymous
       volumes attached to containers"""
    _cmd: str = _dc.field(default="down", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "remove_orphans",
            "volumes",
        ],
        repr=False,
        init=False,
    )
