# DO NOT EDIT: Autogenerated by /Users/micha/dev/external/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeEvents(DockerBaseRunner):
    """
    Usage:  docker compose events [OPTIONS] [SERVICE...]
    Receive real time events from containers.
    """

    json: Optional[bool] = None
    """Output events as a stream of json objects"""
    _cmd: str = "events"
    _options: List[str] = [
        "json",
    ]
