# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeEvents(DockerBaseRunner):
    """
    Usage:  docker compose events [OPTIONS] [SERVICE...]
    Receive real time events from containers
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    json: Optional[bool] = None
    """Output events as a stream of json objects"""
    since: Optional[str] = None
    """Show all events created since timestamp"""
    until: Optional[str] = None
    """Stream events until this timestamp"""
    _cmd: str = "events"
    _options: List[str] = [
        "dry_run",
        "json",
    ]
