# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeEvents(DockerBaseRunner):
    """
    Usage:  docker compose events [OPTIONS] [SERVICE...]
    Receive real time events from containers
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    json: Optional[bool] = None
    """Output events as a stream of json objects"""
    since: Optional[str] = None
    """Show all events created since timestamp"""
    until: Optional[str] = None
    """Stream events until this timestamp"""
    _cmd: str = _dc.field(default="events", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "json",
        ],
        repr=False,
        init=False,
    )
