# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeExec(DockerBaseRunner):
    """
    Usage:  docker compose exec [OPTIONS] SERVICE COMMAND [ARGS...]
    Execute a command in a running container
    """

    detach: Optional[bool] = None
    """Detached mode: Run command in the background"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    env: Optional[list] = None
    """Set environment variables"""
    index: Optional[int] = None
    """Index of the container if service has multiple replicas"""
    no_tty: Optional[bool] = None
    """Disable pseudo-TTY allocation. By default 'docker compose exec' allocates a TTY. (default true)"""
    privileged: Optional[bool] = None
    """Give extended privileges to the process"""
    user: Optional[str] = None
    """Run the command as this user"""
    workdir: Optional[str] = None
    """Path to workdir directory for this command"""
    _cmd: str = _dc.field(default="exec", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "detach",
            "dry_run",
            "no_tty",
            "privileged",
        ],
        repr=False,
        init=False,
    )
