# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeExec(DockerBaseRunner):
    """
    Usage:  docker compose exec [OPTIONS] SERVICE COMMAND [ARGS...]
    Execute a command in a running container
    """

    detach: Optional[bool] = None
    """Detached mode: Run command in the background"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    env: Optional[list] = None
    """Set environment variables"""
    index: Optional[int] = None
    """Index of the container if service has multiple replicas"""
    no_TTY: Optional[bool] = None
    """Disable pseudo-TTY allocation. By default docker compose exec allocates a TTY. (default true)"""
    privileged: Optional[bool] = None
    """Give extended privileges to the process"""
    user: Optional[str] = None
    """Run the command as this user"""
    workdir: Optional[str] = None
    """Path to workdir directory for this command"""
    _cmd: str = "exec"
    _options: List[str] = [
        "detach",
        "dry_run",
        "privileged",
    ]
