# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeExport(DockerBaseRunner):
    """
    Usage:  docker compose export [OPTIONS] SERVICE
    Export a service container's filesystem as a tar archive
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    index: Optional[int] = None
    """index of the container if service has multiple
       replicas."""
    output: Optional[str] = None
    """Write to a file, instead of STDOUT"""
    _cmd: str = "export"
    _options: List[str] = [
        "dry_run",
    ]
