# DO NOT EDIT: Autogenerated by /Users/micha/dev/external/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.17.3

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeImages(DockerBaseRunner):
    """
    Usage:  docker compose images [OPTIONS] [SERVICE...]
    List images used by the created containers
    """

    format: Optional[str] = None
    """Format the output. Values: [table | json]. (default "table")"""
    quiet: Optional[bool] = None
    """Only display IDs"""
    _cmd: str = "images"
    _options: List[str] = [
        "quiet",
    ]
