# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeImages(DockerBaseRunner):
    """
    Usage:  docker compose images [OPTIONS] [SERVICE...]
    List images used by the created containers
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    format: Optional[str] = None
    """Format the output. Values: [table | json] (default "table")"""
    quiet: Optional[bool] = None
    """Only display IDs"""
    _cmd: str = _dc.field(default="images", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "quiet",
        ],
        repr=False,
        init=False,
    )
