# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeKill(DockerBaseRunner):
    """
    Usage:  docker compose kill [OPTIONS] [SERVICE...]
    Force stop service containers
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    remove_orphans: Optional[bool] = None
    """Remove containers for services not defined in
       the Compose file"""
    signal: Optional[str] = None
    """SIGNAL to send to the container (default "SIGKILL")"""
    _cmd: str = "kill"
    _options: List[str] = [
        "dry_run",
        "remove_orphans",
    ]
