# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeLogs(DockerBaseRunner):
    """
    Usage:  docker compose logs [OPTIONS] [SERVICE...]
    View output from containers
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    follow: Optional[bool] = None
    """Follow log output"""
    index: Optional[int] = None
    """index of the container if service has multiple replicas"""
    no_color: Optional[bool] = None
    """Produce monochrome output"""
    no_log_prefix: Optional[bool] = None
    """Don't print prefix in logs"""
    since: Optional[str] = None
    """Show logs since timestamp (e.g. 2013-01-02T13:23:37Z) or relative (e.g. 42m for 42 minutes)"""
    tail: Optional[str] = None
    """Number of lines to show from the end of the logs for each container (default "all")"""
    timestamps: Optional[bool] = None
    """Show timestamps"""
    until: Optional[str] = None
    """Show logs before a timestamp (e.g. 2013-01-02T13:23:37Z) or relative (e.g. 42m for 42 minutes)"""
    _cmd: str = _dc.field(default="logs", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "follow",
            "no_color",
            "no_log_prefix",
            "timestamps",
        ],
        repr=False,
        init=False,
    )
