# DO NOT EDIT: Autogenerated by src/docker_composer/_utils/generate_class.py
# for docker-compose version 1.25.0, build unknown

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeLogs(DockerBaseRunner):
    """
    View output from containers.

    Usage: logs [options] [SERVICE...]

    """

    no_color: Optional[bool] = None
    """Produce monochrome output."""
    follow: Optional[bool] = None
    """Follow log output."""
    timestamps: Optional[bool] = None
    """Show timestamps."""
    tail: Optional[str] = None
    """Number of lines to show from the end of the logs
       for each container."""
    _cmd: str = "logs"
    _options: List[str] = [
        "no_color",
        "follow",
        "timestamps",
    ]
