# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeLs(DockerBaseRunner):
    """
    Usage:  docker compose ls [OPTIONS]
    List running compose projects
    """

    all: Optional[bool] = None
    """Show all stopped Compose projects"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    filter: Optional[str] = None
    """Filter output based on conditions provided"""
    format: Optional[str] = None
    """Format the output. Values: [table | json]
       (default "table")"""
    quiet: Optional[bool] = None
    """Only display project names"""
    _cmd: str = _dc.field(default="ls", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "all",
            "dry_run",
            "quiet",
        ],
        repr=False,
        init=False,
    )
