# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeLs(DockerBaseRunner):
    """
    Usage:  docker compose ls [OPTIONS]
    List running compose projects
    """

    all: Optional[bool] = None
    """Show all stopped Compose projects"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    filter: Optional[str] = None
    """Filter output based on conditions provided"""
    format: Optional[str] = None
    """Format the output. Values: [table | json] (default "table")"""
    quiet: Optional[bool] = None
    """Only display IDs"""
    _cmd: str = "ls"
    _options: List[str] = [
        "all",
        "dry_run",
        "quiet",
    ]
