# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePort(DockerBaseRunner):
    """
    Usage:  docker compose port [OPTIONS] SERVICE PRIVATE_PORT
    Print the public port for a port binding
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    index: Optional[int] = None
    """Index of the container if service has multiple replicas"""
    protocol: Optional[str] = None
    """tcp or udp (default "tcp")"""
    _cmd: str = "port"
    _options: List[str] = [
        "dry_run",
    ]
