# DO NOT EDIT: Autogenerated by src/docker_composer/_utils/generate_class.py
# for docker-compose version 1.25.0, build unknown

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePs(DockerBaseRunner):
    """
    List containers.

    Usage: ps [options] [SERVICE...]

    """

    quiet: Optional[bool] = None
    """Only display IDs"""
    services: Optional[bool] = None
    """Display services"""
    filter: Optional[dict] = None
    """Filter services by a property"""
    all: Optional[bool] = None
    """Show all stopped containers (including those created by the run command)"""
    _cmd: str = "ps"
    _options: List[str] = [
        "quiet",
        "services",
        "all",
    ]
