# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePs(DockerBaseRunner):
    """
    Usage:  docker compose ps [OPTIONS] [SERVICE...]
    List containers
    """

    all: Optional[bool] = None
    """Show all stopped containers (including those created by the run command)"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    filter: Optional[str] = None
    """Filter services by a property (supported filters: status)"""
    format: Optional[str] = None
    """Format output using a custom template:
       'table':            Print output in table format with column headers (default)
       'table TEMPLATE':   Print output in table format using the given Go template
       'json':             Print in JSON format
       'TEMPLATE':         Print output using the given Go template.
       Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates (default "table")"""
    no_trunc: Optional[bool] = None
    """Don't truncate output"""
    orphans: Optional[bool] = None
    """Include orphaned services (not declared by project) (default true)"""
    quiet: Optional[bool] = None
    """Only display IDs"""
    services: Optional[bool] = None
    """Display services"""
    status: Optional[list] = None
    """Filter services by status. Values: [paused | restarting | removing | running | dead | created | exited]"""
    _cmd: str = "ps"
    _options: List[str] = [
        "all",
        "dry_run",
        "no_trunc",
        "orphans",
        "quiet",
        "services",
    ]
