# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePublish(DockerBaseRunner):
    """
    Usage:  docker compose publish [OPTIONS] REPOSITORY[:TAG]
    Publish compose application
    """

    app: Optional[bool] = None
    """Published compose application (includes
       referenced images)"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    oci_version: Optional[str] = None
    """OCI image/artifact specification version
       (automatically determined by default)"""
    resolve_image_digests: Optional[bool] = None
    """Pin image tags to digests"""
    with_env: Optional[bool] = None
    """Include environment variables in the
       published OCI artifact"""
    yes: Optional[bool] = None
    """Assume "yes" as answer to all prompts"""
    _cmd: str = "publish"
    _options: List[str] = [
        "app",
        "dry_run",
        "resolve_image_digests",
        "with_env",
        "yes",
    ]
