# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposePull(DockerBaseRunner):
    """
    Usage:  docker compose pull [OPTIONS] [SERVICE...]
    Pull service images
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    ignore_buildable: Optional[bool] = None
    """Ignore images that can be built"""
    ignore_pull_failures: Optional[bool] = None
    """Pull what it can and ignores images with
       pull failures"""
    include_deps: Optional[bool] = None
    """Also pull services declared as dependencies"""
    policy: Optional[str] = None
    """Apply pull policy ("missing"|"always")"""
    quiet: Optional[bool] = None
    """Pull without printing progress information"""
    _cmd: str = _dc.field(default="pull", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "ignore_buildable",
            "ignore_pull_failures",
            "include_deps",
            "quiet",
        ],
        repr=False,
        init=False,
    )
