# DO NOT EDIT: Autogenerated by /Users/micha/dev/external/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.17.3

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePull(DockerBaseRunner):
    """
    Usage:  docker compose pull [OPTIONS] [SERVICE...]
    Pull service images
    """

    ignore_buildable: Optional[bool] = None
    """Ignore images that can be built."""
    ignore_pull_failures: Optional[bool] = None
    """Pull what it can and ignores images with pull failures."""
    include_deps: Optional[bool] = None
    """Also pull services declared as dependencies."""
    quiet: Optional[bool] = None
    """Pull without printing progress information."""
    _cmd: str = "pull"
    _options: List[str] = [
        "ignore_buildable",
        "ignore_pull_failures",
        "include_deps",
        "quiet",
    ]
