# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePull(DockerBaseRunner):
    """
    Usage:  docker compose pull [OPTIONS] [SERVICE...]
    Pull service images
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    ignore_buildable: Optional[bool] = None
    """Ignore images that can be built"""
    ignore_pull_failures: Optional[bool] = None
    """Pull what it can and ignores images with pull failures"""
    include_deps: Optional[bool] = None
    """Also pull services declared as dependencies"""
    policy: Optional[str] = None
    """Apply pull policy ("missing"|"always")"""
    quiet: Optional[bool] = None
    """Pull without printing progress information"""
    _cmd: str = "pull"
    _options: List[str] = [
        "dry_run",
        "ignore_buildable",
        "ignore_pull_failures",
        "include_deps",
        "quiet",
    ]
