# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposePush(DockerBaseRunner):
    """
    Usage:  docker compose push [OPTIONS] [SERVICE...]
    Push service images
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    ignore_push_failures: Optional[bool] = None
    """Push what it can and ignores images with push failures"""
    include_deps: Optional[bool] = None
    """Also push images of services declared as dependencies"""
    quiet: Optional[bool] = None
    """Push without printing progress information"""
    _cmd: str = _dc.field(default="push", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "ignore_push_failures",
            "include_deps",
            "quiet",
        ],
        repr=False,
        init=False,
    )
