# DO NOT EDIT: Autogenerated by /Users/micha/dev/external/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeRestart(DockerBaseRunner):
    """
    Usage:  docker compose restart [OPTIONS] [SERVICE...]
    Restart service containers
    """

    no_deps: Optional[bool] = None
    """Don't restart dependent services."""
    timeout: Optional[int] = None
    """Specify a shutdown timeout in seconds (default 10)"""
    _cmd: str = "restart"
    _options: List[str] = [
        "no_deps",
    ]
