# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeRm(DockerBaseRunner):
    """
    Usage:  docker compose rm [OPTIONS] [SERVICE...]
    Removes stopped service containers
    By default, anonymous volumes attached to containers will not be removed. You
    can override this with -v. To list all volumes, use "docker volume ls".
    Any data which is not in a volume will be lost.
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    force: Optional[bool] = None
    """Don't ask to confirm removal"""
    stop: Optional[bool] = None
    """Stop the containers, if required, before removing"""
    volumes: Optional[bool] = None
    """Remove any anonymous volumes attached to containers"""
    _cmd: str = _dc.field(default="rm", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "force",
            "stop",
            "volumes",
        ],
        repr=False,
        init=False,
    )
