# DO NOT EDIT: Autogenerated by src/docker_composer/_utils/generate_class.py
# for docker-compose version 1.25.0, build unknown

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeRm(DockerBaseRunner):
    """
    Removes stopped service containers.

    By default, anonymous volumes attached to containers will not be removed. You
    can override this with `-v`. To list all volumes, use `docker volume ls`.

    Any data which is not in a volume will be lost.

    Usage: rm [options] [SERVICE...]

    """

    force: Optional[bool] = None
    """Don't ask to confirm removal"""
    stop: Optional[bool] = None
    """Stop the containers, if required, before removing"""
    v: Optional[bool] = None
    """Remove any anonymous volumes attached to containers"""
    all: Optional[bool] = None
    """Deprecated - no effect."""
    _cmd: str = "rm"
    _options: List[str] = [
        "force",
        "stop",
        "v",
        "all",
    ]
