# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeRun(DockerBaseRunner):
    """
    Usage:  docker compose run [OPTIONS] SERVICE [COMMAND] [ARGS...]
    Run a one-off command on a service
    """

    build: Optional[bool] = None
    """Build image before starting container"""
    cap_add: Optional[list] = None
    """Add Linux capabilities"""
    cap_drop: Optional[list] = None
    """Drop Linux capabilities"""
    detach: Optional[bool] = None
    """Run container in background and print container ID"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    entrypoint: Optional[str] = None
    """Override the entrypoint of the image"""
    env: Optional[list] = None
    """Set environment variables"""
    interactive: Optional[bool] = None
    """Keep STDIN open even if not attached (default true)"""
    label: Optional[list] = None
    """Add or override a label"""
    name: Optional[str] = None
    """Assign a name to the container"""
    no_TTY: Optional[bool] = None
    """Disable pseudo-TTY allocation (default: auto-detected) (default true)"""
    no_deps: Optional[bool] = None
    """Don't start linked services"""
    publish: Optional[list] = None
    """Publish a container's port(s) to the host"""
    quiet_pull: Optional[bool] = None
    """Pull without printing progress information"""
    remove_orphans: Optional[bool] = None
    """Remove containers for services not defined in the Compose file"""
    rm: Optional[bool] = None
    """Automatically remove the container when it exits"""
    service_ports: Optional[bool] = None
    """Run command with all service's ports enabled and mapped to the host"""
    use_aliases: Optional[bool] = None
    """Use the service's network useAliases in the network(s) the container connects to"""
    user: Optional[str] = None
    """Run as specified username or uid"""
    volume: Optional[list] = None
    """Bind mount a volume"""
    workdir: Optional[str] = None
    """Working directory inside the container"""
    _cmd: str = "run"
    _options: List[str] = [
        "build",
        "detach",
        "dry_run",
        "interactive",
        "no_TTY",
        "no_deps",
        "quiet_pull",
        "remove_orphans",
        "rm",
        "service_ports",
        "use_aliases",
    ]
