# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeRun(DockerBaseRunner):
    """
    Usage:  docker compose run [OPTIONS] SERVICE [COMMAND] [ARGS...]
    Run a one-off command on a service
    """

    build: Optional[bool] = None
    """Build image before starting container"""
    cap_add: Optional[list] = None
    """Add Linux capabilities"""
    cap_drop: Optional[list] = None
    """Drop Linux capabilities"""
    detach: Optional[bool] = None
    """Run container in background and print
       container ID"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    entrypoint: Optional[str] = None
    """Override the entrypoint of the image"""
    env: Optional[list] = None
    """Set environment variables"""
    env_from_file: Optional[list] = None
    """Set environment variables from file"""
    interactive: Optional[bool] = None
    """Keep STDIN open even if not attached
       (default true)"""
    label: Optional[list] = None
    """Add or override a label"""
    name: Optional[str] = None
    """Assign a name to the container"""
    no_TTY: Optional[bool] = None
    """Disable pseudo-TTY allocation
       (default: auto-detected) (default true)"""
    no_deps: Optional[bool] = None
    """Don't start linked services"""
    publish: Optional[list] = None
    """Publish a container's port(s) to the host"""
    pull: Optional[str] = None
    """Pull image before running
       ("always"|"missing"|"never") (default
       "policy")"""
    quiet: Optional[bool] = None
    """Don't print anything to STDOUT"""
    quiet_build: Optional[bool] = None
    """Suppress progress output from the
       build process"""
    quiet_pull: Optional[bool] = None
    """Pull without printing progress information"""
    remove_orphans: Optional[bool] = None
    """Remove containers for services not
       defined in the Compose file"""
    rm: Optional[bool] = None
    """Automatically remove the container
       when it exits"""
    service_ports: Optional[bool] = None
    """Run command with all service's ports
       enabled and mapped to the host"""
    use_aliases: Optional[bool] = None
    """Use the service's network useAliases
       in the network(s) the container
       connects to"""
    user: Optional[str] = None
    """Run as specified username or uid"""
    volume: Optional[list] = None
    """Bind mount a volume"""
    workdir: Optional[str] = None
    """Working directory inside the container"""
    _cmd: str = _dc.field(default="run", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "build",
            "detach",
            "dry_run",
            "interactive",
            "no_TTY",
            "no_deps",
            "quiet",
            "quiet_build",
            "quiet_pull",
            "remove_orphans",
            "rm",
            "service_ports",
            "use_aliases",
        ],
        repr=False,
        init=False,
    )
