# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeScale(DockerBaseRunner):
    """
    Usage:  docker compose scale [SERVICE=REPLICAS...]
    Scale services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    no_deps: Optional[bool] = None
    """Don't start linked services"""
    _cmd: str = _dc.field(default="scale", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "no_deps",
        ],
        repr=False,
        init=False,
    )
