# DO NOT EDIT: Autogenerated by src/docker_composer/_utils/generate_class.py
# for docker-compose version 1.25.0, build unknown

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeScale(DockerBaseRunner):
    """
    Set number of containers to run for a service.

    Numbers are specified in the form `service=num` as arguments.
    For example:

        $ docker-compose scale web=2 worker=3

    This command is deprecated. Use the up command with the `--scale` flag
    instead.

    Usage: scale [options] [SERVICE=NUM...]

    """

    timeout: Optional[int] = None
    """Specify a shutdown timeout in seconds.
       (default: 10)"""
    _cmd: str = "scale"
    _options: List[str] = []
