# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeScale(DockerBaseRunner):
    """
    Usage:  docker compose scale [SERVICE=REPLICAS...]
    Scale services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    no_deps: Optional[bool] = None
    """Don't start linked services"""
    _cmd: str = "scale"
    _options: List[str] = [
        "dry_run",
        "no_deps",
    ]
