# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeStart(DockerBaseRunner):
    """
    Usage:  docker compose start [SERVICE...]
    Start services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    wait: Optional[bool] = None
    """Wait for services to be running|healthy.
       Implies detached mode."""
    wait_timeout: Optional[int] = None
    """Maximum duration in seconds to wait for the
       project to be running|healthy"""
    _cmd: str = _dc.field(default="start", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "wait",
        ],
        repr=False,
        init=False,
    )
