# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

from typing import Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeStart(DockerBaseRunner):
    """
    Usage:  docker compose start [SERVICE...]
    Start services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    wait: Optional[bool] = None
    """Wait for services to be running|healthy.
       Implies detached mode."""
    wait_timeout: Optional[int] = None
    """Maximum duration in seconds to wait for the
       project to be running|healthy"""
    _cmd: str = "start"
    _options: list[str] = [
        "dry_run",
        "wait",
    ]
