# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeStats(DockerBaseRunner):
    """
    Usage:  docker compose stats [OPTIONS] [SERVICE]
    Display a live stream of container(s) resource usage statistics
    """

    all: Optional[bool] = None
    """Show all containers (default shows just running)"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    format: Optional[str] = None
    """Format output using a custom template:
       'table':            Print output in table format with column headers (default)
       'table TEMPLATE':   Print output in table format using the given Go template
       'json':             Print in JSON format
       'TEMPLATE':         Print output using the given Go template.
       Refer to https://docs.docker.com/engine/cli/formatting/ for more information about formatting output with templates"""
    no_stream: Optional[bool] = None
    """Disable streaming stats and only pull the first result"""
    no_trunc: Optional[bool] = None
    """Do not truncate output"""
    _cmd: str = _dc.field(default="stats", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "all",
            "dry_run",
            "no_stream",
            "no_trunc",
        ],
        repr=False,
        init=False,
    )
