# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeStop(DockerBaseRunner):
    """
    Usage:  docker compose stop [OPTIONS] [SERVICE...]
    Stop services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    timeout: Optional[int] = None
    """Specify a shutdown timeout in seconds"""
    _cmd: str = "stop"
    _options: List[str] = [
        "dry_run",
    ]
