# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeStop(DockerBaseRunner):
    """
    Usage:  docker compose stop [OPTIONS] [SERVICE...]
    Stop services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    timeout: Optional[int] = None
    """Specify a shutdown timeout in seconds"""
    _cmd: str = _dc.field(default="stop", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
        ],
        repr=False,
        init=False,
    )
