# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeTop(DockerBaseRunner):
    """
    Usage:  docker compose top [SERVICES...]
    Display the running processes
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    _cmd: str = "top"
    _options: List[str] = [
        "dry_run",
    ]
