# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeUnpause(DockerBaseRunner):
    """
    Usage:  docker compose unpause [SERVICE...]
    Unpause services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    _cmd: str = _dc.field(default="unpause", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
        ],
        repr=False,
        init=False,
    )
