# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

from typing import Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeUnpause(DockerBaseRunner):
    """
    Usage:  docker compose unpause [SERVICE...]
    Unpause services
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    _cmd: str = "unpause"
    _options: list[str] = [
        "dry_run",
    ]
