# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.3

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeVersion(DockerBaseRunner):
    """
    Usage:  docker compose version [OPTIONS]
    Show the Docker Compose version information
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    format: Optional[str] = None
    """Format the output. Values: [pretty | json]. (Default: pretty)"""
    short: Optional[bool] = None
    """Shows only Compose's version number"""
    _cmd: str = _dc.field(default="version", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "short",
        ],
        repr=False,
        init=False,
    )
