# DO NOT EDIT: Autogenerated by /Users/micha/dev/external/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.17.3

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeVersion(DockerBaseRunner):
    """
    Usage:  docker compose version [OPTIONS]
    Show the Docker Compose version information
    """

    format: Optional[str] = None
    """Format the output. Values: [pretty | json]. (Default: pretty)"""
    short: Optional[bool] = None
    """Shows only Compose's version number."""
    _cmd: str = "version"
    _options: List[str] = [
        "short",
    ]
