# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeVolumes(DockerBaseRunner):
    """
    Usage:  docker compose volumes [OPTIONS] [SERVICE...]
    List volumes
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    format: Optional[str] = None
    """Format output using a custom template:
       'table':            Print output in table format
       with column headers (default)
       'table TEMPLATE':   Print output in table format
       using the given Go template
       'json':             Print in JSON format
       'TEMPLATE':         Print output using the given
       Go template.
       Refer to https://docs.docker.com/go/formatting/
       for more information about formatting output with
       templates (default "table")"""
    quiet: Optional[bool] = None
    """Only display volume names"""
    _cmd: str = _dc.field(default="volumes", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "quiet",
        ],
        repr=False,
        init=False,
    )
