# DO NOT EDIT: Autogenerated by /Users/micha/dev/docker-composer/src/docker_composer/_utils/generate_class.py
# for Docker Compose version v2.29.7-desktop.1

from typing import List, Optional

import attr

from docker_composer.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeWait(DockerBaseRunner):
    """
    Usage:  docker compose wait SERVICE [SERVICE...] [OPTIONS]
    Block until containers of all (or specified) services stop.
    """

    down_project: Optional[bool] = None
    """Drops project when the first container stops"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    _cmd: str = "wait"
    _options: List[str] = [
        "down_project",
        "dry_run",
    ]
