# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeWait(DockerBaseRunner):
    """
    Usage:  docker compose wait SERVICE [SERVICE...] [OPTIONS]
    Block until containers of all (or specified) services stop.
    """

    down_project: Optional[bool] = None
    """Drops project when the first container stops"""
    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    _cmd: str = _dc.field(default="wait", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "down_project",
            "dry_run",
        ],
        repr=False,
        init=False,
    )
