# DO NOT EDIT: Autogenerated by docker_composer/_utils/generate_class.py
# for Docker Compose version v5.1.0

import dataclasses as _dc
from typing import Optional

from docker_composer.base import DockerBaseRunner


@_dc.dataclass()
class DockerComposeWatch(DockerBaseRunner):
    """
    Usage:  docker compose watch [SERVICE...]
    Watch build context for service and rebuild/refresh containers when files are updated
    """

    dry_run: Optional[bool] = None
    """Execute command in dry run mode"""
    no_up: Optional[bool] = None
    """Do not build & start services before watching"""
    prune: Optional[bool] = None
    """Prune dangling images on rebuild (default true)"""
    quiet: Optional[bool] = None
    """hide build output"""
    _cmd: str = _dc.field(default="watch", repr=False, init=False)
    _options: list[str] = _dc.field(
        default_factory=lambda: [
            "dry_run",
            "no_up",
            "prune",
            "quiet",
        ],
        repr=False,
        init=False,
    )
